package com.enlacetpe.ticketapi.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.enlacetpe.ticketapi.model.SdmCallReqModel;

@Repository
public interface SdmCallReqRepository extends JpaRepository<SdmCallReqModel, Long> {

	public List<SdmCallReqModel> findByRefNum(String refNum);

	public List<SdmCallReqModel> findByStatus(String status);

	public List<SdmCallReqModel> findByCategory(String category);

	public List<SdmCallReqModel> findByType(String type);

	public List<SdmCallReqModel> findByCustomerInAndType(List<String> customers, String type);

	public List<SdmCallReqModel> findByCustomerInAndTypeAndCloseDateIsNull(List<String> customers, String type);

	public List<SdmCallReqModel> findByAffectedRcInAndTypeAndCloseDateIsNull(List<String> ci, String type);

	public List<SdmCallReqModel> findByAffectedRcInAndTypeAndStatusIn(List<String> ci, String type, String[] status);

	public List<SdmCallReqModel> findByCustomerAndCategoryAndTypeAndActiveFlag(String customer, String category,
			String type, Integer active);

	public List<SdmCallReqModel> findByAffectedRcAndCategoryAndTypeAndActiveFlag(String ci, String category,
			String type, Integer active);

	public List<SdmCallReqModel> findByAffectedRcAndActiveFlag(String affectedRc, Integer activeFlag);

	public List<SdmCallReqModel> findByAffectedRcAndActiveFlagAndDescription(String affectedRc, Integer activeFlag,
			String description);

	public List<SdmCallReqModel> findByActiveFlagAndAffectedRcAndStatusNot(Integer active, String affectedRc,
			String status);

	public SdmCallReqModel findByTenant(String tenant);

	@Query(value = "SELECT \r\n" + "CR.REF_NUM REFNUM,\r\n" + "OW.RESOURCE_NAME TFE,\r\n" + "CTN.NAME TENANT,\r\n"
			+ "CR.SUMMARY RESUMEN,\r\n" + "PR.SYM PRIORIDAD,\r\n" + "PG.SYM CATEGORIA,\r\n" + "ST.SYM ESTADO,\r\n"
			+ "CASE\r\n"
			+ "WHEN CC4.LAST_NAME IS NOT NULL AND CC4.FIRST_NAME IS NOT NULL AND CC4.MIDDLE_NAME IS NOT NULL THEN CONCAT(CC4.LAST_NAME, ', ', CC4.FIRST_NAME, ' ', CC4.MIDDLE_NAME)\r\n"
			+ "WHEN CC4.LAST_NAME IS NOT NULL AND CC4.FIRST_NAME IS NOT NULL AND CC4.MIDDLE_NAME IS NULL THEN CONCAT(CC4.LAST_NAME, ', ', CC4.FIRST_NAME)\r\n"
			+ "WHEN CC4.LAST_NAME AND CC4.FIRST_NAME AND CC4.MIDDLE_NAME IS NOT NULL THEN CONCAT(CC4.LAST_NAME, ', ', CC4.FIRST_NAME, ' ', CC4.MIDDLE_NAME)\r\n"
			+ "END ASIGNADO,\r\n" + "CC4.FIRST_NAME ASIGNADO_PRIMERNOMBRE,\r\n"
			+ "CC4.MIDDLE_NAME ASIGNADO_SEGUNDONOMBRE,\r\n" + "CC4.LAST_NAME ASIGNADO_APELLIDO,\r\n" + "CASE\r\n"
			+ "WHEN CC2.LAST_NAME IS NOT NULL AND CC2.FIRST_NAME IS NOT NULL AND CC2.MIDDLE_NAME IS NOT NULL THEN CONCAT(CC2.LAST_NAME, ', ', CC2.FIRST_NAME, ' ', CC2.MIDDLE_NAME)\r\n"
			+ "WHEN CC2.LAST_NAME IS NOT NULL AND CC2.FIRST_NAME IS NOT NULL AND CC2.MIDDLE_NAME IS NULL THEN CONCAT(CC2.LAST_NAME, ', ', CC2.FIRST_NAME)\r\n"
			+ "WHEN CC2.LAST_NAME AND CC2.FIRST_NAME AND CC2.MIDDLE_NAME IS NOT NULL THEN CONCAT(CC2.LAST_NAME, ', ', CC2.FIRST_NAME, ' ', CC2.MIDDLE_NAME)\r\n"
			+ "END Usuario_Final_Afectado_Cliente,\r\n" + "CC2.FIRST_NAME CLIENTEAFECTADO_PRIMERNOMBRE,\r\n"
			+ "CC2.MIDDLE_NAME CLIENTEAFECTADO_SEGUNDONOMBRE,\r\n" + "CC2.LAST_NAME CLIENTEAFECTADO_LAST_NAME,\r\n"
			+ "CR.DESCRIPTION,\r\n" + "CASE\r\n"
			+ "WHEN CC1.LAST_NAME IS NOT NULL AND CC1.FIRST_NAME IS NOT NULL AND CC1.MIDDLE_NAME IS NOT NULL THEN CONCAT(CC1.LAST_NAME, ', ', CC1.FIRST_NAME, ' ', CC1.MIDDLE_NAME)\r\n"
			+ "WHEN CC1.LAST_NAME IS NOT NULL AND CC1.FIRST_NAME IS NOT NULL AND CC1.MIDDLE_NAME IS NULL THEN CONCAT(CC1.LAST_NAME, ', ', CC1.FIRST_NAME)\r\n"
			+ "WHEN CC1.LAST_NAME AND CC1.FIRST_NAME AND CC1.MIDDLE_NAME IS NOT NULL THEN CONCAT(CC1.LAST_NAME, ', ', CC1.FIRST_NAME, ' ', CC1.MIDDLE_NAME)\r\n"
			+ "END AS SOLICITANTE,\r\n" + "CC5.LAST_NAME GRUPO,\r\n" + "UR.SYM URGENCIA,\r\n" + "IM.SYM IMPACTO,\r\n"
			+ "CR.ZDIAG_INICIAL DIAGNOSTICO_INICIAL,\r\n" + "ZD.SYM DIAGNOSTICO_FINAL,\r\n" + "ZS.SYM SOLUCION,\r\n"
			+ "CR.ZFECHA_SOL FECHA_HORA_DE_SOLUCION,\r\n" + "CR.OPEN_DATE FECHA_HORA_DE_APERTURA,\r\n"
			+ "CR.LAST_MOD_DT ULTIMA_MODIFICACIÓN,\r\n" + "CR.RESOLVE_DATE FECHA_HORA_DE_NOTIFICACION_DE_SOLUCION,\r\n"
			+ "CR.CLOSE_DATE Fecha_Hora_de_Cierre,\r\n" + "CR.ZTIEMPO_FALLA_TPE TIEMPO_FALLA_ENLACE,\r\n"
			+ "CR.ZTIEMPO_FALLA_CTE TIEMPO_FALLA_CTE,\r\n" + "OW.RESOURCE_NAME CI,\r\n"
			+ "CR.ZES_PROACTIVO_REACTIVO,\r\n" + "CR.ZTIEMPO_FALLA_PROV TIEMPO_FALLA_PROVEEDOR,\r\n"
			+ "CR.ZTIEMPO_FALLA_TERCEROS TIEMPO_FALLA_TERCEROS,\r\n" + "CR.MACRO_PREDICT_VIOL,\r\n"
			+ "CR.SLA_VIOLATION,\r\n" + "CR.EXTERNAL_SYSTEM_TICKET,\r\n" + "OW.IP_ADDRESS, \r\n"
			+ "OW2.RESOURCE_NAME \r\n" + "FROM \r\n" + "SDM_CALL_REQ CR\r\n"
			+ "LEFT JOIN SDM_CA_CONTACT CC1 ON CR.REQUESTED_BY = CC1.CONTACT_UUID\r\n"
			+ "LEFT JOIN SDM_CA_CONTACT CC2 ON CR.CUSTOMER = CC2.CONTACT_UUID\r\n"
			+ "LEFT JOIN SDM_PROB_CTG PG ON CR.CATEGORY = PG.PERSID\r\n"
			+ "LEFT JOIN SDM_CR_STAT ST ON CR.STATUS = ST.CODE \r\n"
			+ "LEFT JOIN SDM_PRI PR ON CR.PRIORITY = PR.ENUM\r\n"
			+ "LEFT JOIN SDM_CA_CONTACT CC4 ON CR.ASSIGNEE = CC4.CONTACT_UUID\r\n"
			+ "LEFT JOIN SDM_CA_CONTACT CC5 ON CR.GROUP_ID = CC5.CONTACT_UUID\r\n"
			+ "LEFT JOIN SDM_URGNCY UR ON CR.URGENCY = UR.ENUM\r\n"
			+ "LEFT JOIN SDM_IMPACT IM ON CR.IMPACT = IM.ENUM\r\n"
			+ "LEFT JOIN SDM_CA_OWNED_RESOURCE OW ON AFFECTED_RC = OW.OWN_RESOURCE_UUID\r\n"
			+ "LEFT JOIN SDM_ZDIAGNOSTICO ZD ON CR.ZDIAGNOSTICO_ID = ZD.ID\r\n"
			+ "LEFT JOIN SDM_ZSOLUCION ZS ON CR.ZSOLUCION_ID = ZS.ID\r\n"
			+ "LEFT JOIN SDM_CA_TENANT CTN ON CR.TENANT = CTN.ID \r\n"
			+ "LEFT JOIN SDM_BUSMGT BUS ON OW.OWN_RESOURCE_UUID = BUS.hier_child \r\n"
			+ "LEFT JOIN SDM_CA_OWNED_RESOURCE OW2 ON BUS.hier_parent = OW2.OWN_RESOURCE_UUID \r\n"
			+ "WHERE CR.AFFECTED_RC in (:puntas)\r\n" + "AND CR.TYPE = 'I'\r\n"
			+ "AND CR.STATUS IN(\"OP\",\"WIP\",\"HOLD\",\"AEUR\",\"AWTVNDR\",\"ZPNDTRCR\",\"ZREJSF\",\"RE\",\"ZPRE\")"
			+ "AND OW2.INACTIVE = 0 \r\n"
			+ "AND OW2.RESOURCE_CLASS = (SELECT ID FROM SDM_CA_RESOURCE_CLASS WHERE NAME = (:clase)) \r\n"
			+ "ORDER BY CR.OPEN_DATE desc", nativeQuery = true)
	public abstract List<Object> getTicketsActivos(@Param("puntas") List<String> puntas,@Param("clase") String clase);

	@Query(value = "SELECT \r\n" + "CR.REF_NUM REFNUM,\r\n" + "OW.RESOURCE_NAME TFE,\r\n" + "CTN.NAME TENANT,\r\n"
			+ "CR.SUMMARY RESUMEN,\r\n" + "PR.SYM PRIORIDAD,\r\n" + "PG.SYM CATEGORIA,\r\n" + "ST.SYM ESTADO,\r\n"
			+ "CASE\r\n"
			+ "WHEN CC4.LAST_NAME IS NOT NULL AND CC4.FIRST_NAME IS NOT NULL AND CC4.MIDDLE_NAME IS NOT NULL THEN CONCAT(CC4.LAST_NAME, ', ', CC4.FIRST_NAME, ' ', CC4.MIDDLE_NAME)\r\n"
			+ "WHEN CC4.LAST_NAME IS NOT NULL AND CC4.FIRST_NAME IS NOT NULL AND CC4.MIDDLE_NAME IS NULL THEN CONCAT(CC4.LAST_NAME, ', ', CC4.FIRST_NAME)\r\n"
			+ "WHEN CC4.LAST_NAME AND CC4.FIRST_NAME AND CC4.MIDDLE_NAME IS NOT NULL THEN CONCAT(CC4.LAST_NAME, ', ', CC4.FIRST_NAME, ' ', CC4.MIDDLE_NAME)\r\n"
			+ "END ASIGNADO,\r\n" + "CC4.FIRST_NAME ASIGNADO_PRIMERNOMBRE,\r\n"
			+ "CC4.MIDDLE_NAME ASIGNADO_SEGUNDONOMBRE,\r\n" + "CC4.LAST_NAME ASIGNADO_APELLIDO,\r\n" + "CASE\r\n"
			+ "WHEN CC2.LAST_NAME IS NOT NULL AND CC2.FIRST_NAME IS NOT NULL AND CC2.MIDDLE_NAME IS NOT NULL THEN CONCAT(CC2.LAST_NAME, ', ', CC2.FIRST_NAME, ' ', CC2.MIDDLE_NAME)\r\n"
			+ "WHEN CC2.LAST_NAME IS NOT NULL AND CC2.FIRST_NAME IS NOT NULL AND CC2.MIDDLE_NAME IS NULL THEN CONCAT(CC2.LAST_NAME, ', ', CC2.FIRST_NAME)\r\n"
			+ "WHEN CC2.LAST_NAME AND CC2.FIRST_NAME AND CC2.MIDDLE_NAME IS NOT NULL THEN CONCAT(CC2.LAST_NAME, ', ', CC2.FIRST_NAME, ' ', CC2.MIDDLE_NAME)\r\n"
			+ "END Usuario_Final_Afectado_Cliente,\r\n" + "CC2.FIRST_NAME CLIENTEAFECTADO_PRIMERNOMBRE,\r\n"
			+ "CC2.MIDDLE_NAME CLIENTEAFECTADO_SEGUNDONOMBRE,\r\n" + "CC2.LAST_NAME CLIENTEAFECTADO_LAST_NAME,\r\n"
			+ "CR.DESCRIPTION,\r\n" + "CASE\r\n"
			+ "WHEN CC1.LAST_NAME IS NOT NULL AND CC1.FIRST_NAME IS NOT NULL AND CC1.MIDDLE_NAME IS NOT NULL THEN CONCAT(CC1.LAST_NAME, ', ', CC1.FIRST_NAME, ' ', CC1.MIDDLE_NAME)\r\n"
			+ "WHEN CC1.LAST_NAME IS NOT NULL AND CC1.FIRST_NAME IS NOT NULL AND CC1.MIDDLE_NAME IS NULL THEN CONCAT(CC1.LAST_NAME, ', ', CC1.FIRST_NAME)\r\n"
			+ "WHEN CC1.LAST_NAME AND CC1.FIRST_NAME AND CC1.MIDDLE_NAME IS NOT NULL THEN CONCAT(CC1.LAST_NAME, ', ', CC1.FIRST_NAME, ' ', CC1.MIDDLE_NAME)\r\n"
			+ "END AS SOLICITANTE,\r\n" + "CC5.LAST_NAME GRUPO,\r\n" + "UR.SYM URGENCIA,\r\n" + "IM.SYM IMPACTO,\r\n"
			+ "CR.ZDIAG_INICIAL DIAGNOSTICO_INICIAL,\r\n" + "ZD.SYM DIAGNOSTICO_FINAL,\r\n" + "ZS.SYM SOLUCION,\r\n"
			+ "CR.ZFECHA_SOL FECHA_HORA_DE_SOLUCION,\r\n" + "CR.OPEN_DATE FECHA_HORA_DE_APERTURA,\r\n"
			+ "CR.LAST_MOD_DT ULTIMA_MODIFICACIÓN,\r\n" + "CR.RESOLVE_DATE FECHA_HORA_DE_NOTIFICACION_DE_SOLUCION,\r\n"
			+ "CR.CLOSE_DATE Fecha_Hora_de_Cierre,\r\n" + "CR.ZTIEMPO_FALLA_TPE TIEMPO_FALLA_ENLACE,\r\n"
			+ "CR.ZTIEMPO_FALLA_CTE TIEMPO_FALLA_CTE,\r\n" + "OW.RESOURCE_NAME CI,\r\n"
			+ "CR.ZES_PROACTIVO_REACTIVO,\r\n" + "CR.ZTIEMPO_FALLA_PROV TIEMPO_FALLA_PROVEEDOR,\r\n"
			+ "CR.ZTIEMPO_FALLA_TERCEROS TIEMPO_FALLA_TERCEROS,\r\n" + "CR.MACRO_PREDICT_VIOL,\r\n"
			+ "CR.SLA_VIOLATION,\r\n" + "CR.EXTERNAL_SYSTEM_TICKET,\r\n" + "OW.IP_ADDRESS, \r\n"
			+ "OW2.RESOURCE_NAME \r\n" + "FROM \r\n" + "SDM_CALL_REQ CR\r\n"
			+ "LEFT JOIN SDM_CA_CONTACT CC1 ON CR.REQUESTED_BY = CC1.CONTACT_UUID\r\n"
			+ "LEFT JOIN SDM_CA_CONTACT CC2 ON CR.CUSTOMER = CC2.CONTACT_UUID\r\n"
			+ "LEFT JOIN SDM_PROB_CTG PG ON CR.CATEGORY = PG.PERSID\r\n"
			+ "LEFT JOIN SDM_CR_STAT ST ON CR.STATUS = ST.CODE \r\n"
			+ "LEFT JOIN SDM_PRI PR ON CR.PRIORITY = PR.ENUM\r\n"
			+ "LEFT JOIN SDM_CA_CONTACT CC4 ON CR.ASSIGNEE = CC4.CONTACT_UUID\r\n"
			+ "LEFT JOIN SDM_CA_CONTACT CC5 ON CR.GROUP_ID = CC5.CONTACT_UUID\r\n"
			+ "LEFT JOIN SDM_URGNCY UR ON CR.URGENCY = UR.ENUM\r\n"
			+ "LEFT JOIN SDM_IMPACT IM ON CR.IMPACT = IM.ENUM\r\n"
			+ "LEFT JOIN SDM_CA_OWNED_RESOURCE OW ON AFFECTED_RC = OW.OWN_RESOURCE_UUID\r\n"
			+ "LEFT JOIN SDM_ZDIAGNOSTICO ZD ON CR.ZDIAGNOSTICO_ID = ZD.ID\r\n"
			+ "LEFT JOIN SDM_ZSOLUCION ZS ON CR.ZSOLUCION_ID = ZS.ID\r\n"
			+ "LEFT JOIN SDM_BUSMGT BUS ON OW.OWN_RESOURCE_UUID = BUS.hier_child \r\n"
			+ "LEFT JOIN SDM_CA_OWNED_RESOURCE OW2 ON BUS.hier_parent = OW2.OWN_RESOURCE_UUID \r\n"
			+ "LEFT JOIN SDM_CA_TENANT CTN ON CR.TENANT = CTN.ID \r\n"
			+ "LEFT JOIN SDM_BUSMGT BUS ON OW.OWN_RESOURCE_UUID = BUS.hier_child \r\n"
			+ "LEFT JOIN SDM_CA_OWNED_RESOURCE OW2 ON BUS.hier_parent = OW2.OWN_RESOURCE_UUID \r\n"
			+ "WHERE CR.REF_NUM = :refNum", nativeQuery = true)
	public abstract List<Object> getRefNum(@Param("refNum") String refNum);

	@Query(value = "SELECT REF_NUM FROM SDM_CALL_REQ WHERE REF_NUM IN (:tickets) AND ACTIVE_FLAG = 0", nativeQuery = true)
	public abstract List<Object> getTicketsActivosByRefNum(@Param("tickets") List<String> tickets);

	@Query(value = "SELECT \r\n" + "CR.REF_NUM REFNUM, \r\n" + "OW.RESOURCE_NAME TFE, \r\n" + "CTN.NAME TENANT,\r\n"
			+ "CR.SUMMARY RESUMEN,\r\n" + "PR.SYM PRIORIDAD,\r\n" + "PG.SYM CATEGORIA, \r\n" + "ST.SYM ESTADO,\r\n"
			+ "CASE \r\n"
			+ "WHEN CC4.LAST_NAME IS NOT NULL AND CC4.FIRST_NAME IS NOT NULL AND CC4.MIDDLE_NAME IS NOT NULL THEN CONCAT(CC4.LAST_NAME, ', ', CC4.FIRST_NAME, ' ', CC4.MIDDLE_NAME) \r\n"
			+ "WHEN CC4.LAST_NAME IS NOT NULL AND CC4.FIRST_NAME IS NOT NULL AND CC4.MIDDLE_NAME IS NULL THEN CONCAT(CC4.LAST_NAME, ', ', CC4.FIRST_NAME)\r\n"
			+ "WHEN CC4.LAST_NAME AND CC4.FIRST_NAME AND CC4.MIDDLE_NAME IS NOT NULL THEN CONCAT(CC4.LAST_NAME, ', ', CC4.FIRST_NAME, ' ', CC4.MIDDLE_NAME)\r\n"
			+ "END ASIGNADO,\r\n" + "CC4.FIRST_NAME ASIGNADO_PRIMERNOMBRE, \r\n"
			+ "CC4.MIDDLE_NAME ASIGNADO_SEGUNDONOMBRE,\r\n" + "CC4.LAST_NAME ASIGNADO_APELLIDO,\r\n" + "CASE\r\n"
			+ "WHEN CC2.LAST_NAME IS NOT NULL AND CC2.FIRST_NAME IS NOT NULL AND CC2.MIDDLE_NAME IS NOT NULL THEN CONCAT(CC2.LAST_NAME, ', ', CC2.FIRST_NAME, ' ', CC2.MIDDLE_NAME)\r\n"
			+ "WHEN CC2.LAST_NAME IS NOT NULL AND CC2.FIRST_NAME IS NOT NULL AND CC2.MIDDLE_NAME IS NULL THEN CONCAT(CC2.LAST_NAME, ', ', CC2.FIRST_NAME)\r\n"
			+ "WHEN CC2.LAST_NAME AND CC2.FIRST_NAME AND CC2.MIDDLE_NAME IS NOT NULL THEN CONCAT(CC2.LAST_NAME, ', ', CC2.FIRST_NAME, ' ', CC2.MIDDLE_NAME)\r\n"
			+ "END Usuario_Final_Afectado_Cliente,\r\n" + "CC2.FIRST_NAME CLIENTEAFECTADO_PRIMERNOMBRE,\r\n"
			+ "CC2.MIDDLE_NAME CLIENTEAFECTADO_SEGUNDONOMBRE,\r\n" + "CC2.LAST_NAME CLIENTEAFECTADO_LAST_NAME,\r\n"
			+ "CR.DESCRIPTION,\r\n" + "CASE\r\n"
			+ "WHEN CC1.LAST_NAME IS NOT NULL AND CC1.FIRST_NAME IS NOT NULL AND CC1.MIDDLE_NAME IS NOT NULL THEN CONCAT(CC1.LAST_NAME, ', ', CC1.FIRST_NAME, ' ', CC1.MIDDLE_NAME) \r\n"
			+ "WHEN CC1.LAST_NAME IS NOT NULL AND CC1.FIRST_NAME IS NOT NULL AND CC1.MIDDLE_NAME IS NULL THEN CONCAT(CC1.LAST_NAME, ', ', CC1.FIRST_NAME) \r\n"
			+ "WHEN CC1.LAST_NAME AND CC1.FIRST_NAME AND CC1.MIDDLE_NAME IS NOT NULL THEN CONCAT(CC1.LAST_NAME, ', ', CC1.FIRST_NAME, ' ', CC1.MIDDLE_NAME)\r\n"
			+ "END AS SOLICITANTE,\r\n" + "CC5.LAST_NAME GRUPO,\r\n" + "UR.SYM URGENCIA,\r\n" + "IM.SYM IMPACTO,\r\n"
			+ "CR.ZDIAG_INICIAL DIAGNOSTICO_INICIAL,\r\n" + "ZD.SYM DIAGNOSTICO_FINAL,\r\n" + "ZS.SYM SOLUCION,\r\n"
			+ "CR.ZFECHA_SOL FECHA_HORA_DE_SOLUCION,\r\n" + "CR.OPEN_DATE FECHA_HORA_DE_APERTURA,\r\n"
			+ "CR.LAST_MOD_DT ULTIMA_MODIFICACIÓN, \r\n" + "CR.RESOLVE_DATE FECHA_HORA_DE_NOTIFICACION_DE_SOLUCION,\r\n"
			+ "CR.CLOSE_DATE Fecha_Hora_de_Cierre,\r\n" + "CR.ZTIEMPO_FALLA_TPE TIEMPO_FALLA_ENLACE,\r\n"
			+ "CR.ZTIEMPO_FALLA_CTE TIEMPO_FALLA_CTE,\r\n" + "OW.RESOURCE_NAME CI, \r\n"
			+ "CR.ZES_PROACTIVO_REACTIVO,\r\n" + "CR.ZTIEMPO_FALLA_PROV TIEMPO_FALLA_PROVEEDOR,\r\n"
			+ "CR.ZTIEMPO_FALLA_TERCEROS TIEMPO_FALLA_TERCEROS,\r\n" + "CR.MACRO_PREDICT_VIOL, \r\n"
			+ "CR.SLA_VIOLATION,\r\n" + "CR.EXTERNAL_SYSTEM_TICKET,\r\n" + "OW.IP_ADDRESS, \r\n" + "''" + "FROM  \r\n"
			+ "SDM_CALL_REQ CR\r\n" + "LEFT JOIN SDM_CA_CONTACT CC1 ON CR.REQUESTED_BY = CC1.CONTACT_UUID\r\n"
			+ "LEFT JOIN SDM_CA_CONTACT CC2 ON CR.CUSTOMER = CC2.CONTACT_UUID \r\n"
			+ "LEFT JOIN SDM_PROB_CTG PG ON CR.CATEGORY = PG.PERSID\r\n"
			+ "LEFT JOIN SDM_CR_STAT ST ON CR.STATUS = ST.CODE  \r\n"
			+ "LEFT JOIN SDM_PRI PR ON CR.PRIORITY = PR.ENUM\r\n"
			+ "LEFT JOIN SDM_CA_CONTACT CC4 ON CR.ASSIGNEE = CC4.CONTACT_UUID\r\n"
			+ "LEFT JOIN SDM_CA_CONTACT CC5 ON CR.GROUP_ID = CC5.CONTACT_UUID\r\n"
			+ "LEFT JOIN SDM_URGNCY UR ON CR.URGENCY = UR.ENUM \r\n"
			+ "LEFT JOIN SDM_IMPACT IM ON CR.IMPACT = IM.ENUM\r\n"
			+ "LEFT JOIN SDM_CA_OWNED_RESOURCE OW ON AFFECTED_RC = OW.OWN_RESOURCE_UUID\r\n"
			+ "LEFT JOIN SDM_ZDIAGNOSTICO ZD ON CR.ZDIAGNOSTICO_ID = ZD.ID \r\n"
			+ "LEFT JOIN SDM_ZSOLUCION ZS ON CR.ZSOLUCION_ID = ZS.ID\r\n"
			+ "LEFT JOIN SDM_CA_TENANT CTN ON CR.TENANT = CTN.ID \r\n"
			+ "WHERE CR.TYPE='I' AND CR.STATUS != 'RE' AND CR.ACTIVE_FLAG = '1'\r\n"
			+ "AND CR.GROUP_ID IN (:refNum)", nativeQuery = true)
	public abstract List<Object> getTicketByGroup(@Param("refNum") List<String> refNum);

	@Query(value = "SELECT\r\n" + "CR.REF_NUM REFNUM,\r\n" + "OW.RESOURCE_NAME TFE,\r\n" + "CTN.NAME TENANT,\r\n"
			+ "CR.SUMMARY RESUMEN,\r\n" + "PR.SYM PRIORIDAD,\r\n" + "PG.SYM CATEGORIA,\r\n" + "ST.SYM ESTADO,\r\n"
			+ "CASE\r\n"
			+ "WHEN CC4.LAST_NAME IS NOT NULL AND CC4.FIRST_NAME IS NOT NULL AND CC4.MIDDLE_NAME IS NOT NULL THEN CONCAT(CC4.LAST_NAME, ', ', CC4.FIRST_NAME, ' ', CC4.MIDDLE_NAME)\r\n"
			+ "WHEN CC4.LAST_NAME IS NOT NULL AND CC4.FIRST_NAME IS NOT NULL AND CC4.MIDDLE_NAME IS NULL THEN CONCAT(CC4.LAST_NAME, ', ', CC4.FIRST_NAME)\r\n"
			+ "WHEN CC4.LAST_NAME AND CC4.FIRST_NAME AND CC4.MIDDLE_NAME IS NOT NULL THEN CONCAT(CC4.LAST_NAME, ', ', CC4.FIRST_NAME, ' ', CC4.MIDDLE_NAME)\r\n"
			+ "END ASIGNADO,\r\n" + "CC4.FIRST_NAME ASIGNADO_PRIMERNOMBRE,\r\n"
			+ "CC4.MIDDLE_NAME ASIGNADO_SEGUNDONOMBRE,\r\n" + "CC4.LAST_NAME ASIGNADO_APELLIDO,\r\n" + "CASE\r\n"
			+ "WHEN CC2.LAST_NAME IS NOT NULL AND CC2.FIRST_NAME IS NOT NULL AND CC2.MIDDLE_NAME IS NOT NULL THEN CONCAT(CC2.LAST_NAME, ', ', CC2.FIRST_NAME, ' ', CC2.MIDDLE_NAME)\r\n"
			+ "WHEN CC2.LAST_NAME IS NOT NULL AND CC2.FIRST_NAME IS NOT NULL AND CC2.MIDDLE_NAME IS NULL THEN CONCAT(CC2.LAST_NAME, ', ', CC2.FIRST_NAME)\r\n"
			+ "WHEN CC2.LAST_NAME AND CC2.FIRST_NAME AND CC2.MIDDLE_NAME IS NOT NULL THEN CONCAT(CC2.LAST_NAME, ', ', CC2.FIRST_NAME, ' ', CC2.MIDDLE_NAME) \r\n"
			+ "END Usuario_Final_Afectado_Cliente,\r\n" + "CC2.FIRST_NAME CLIENTEAFECTADO_PRIMERNOMBRE,\r\n"
			+ "CC2.MIDDLE_NAME CLIENTEAFECTADO_SEGUNDONOMBRE,\r\n" + "CC2.LAST_NAME CLIENTEAFECTADO_LAST_NAME, \r\n"
			+ "CR.DESCRIPTION,\r\n" + "CASE\r\n"
			+ "WHEN CC1.LAST_NAME IS NOT NULL AND CC1.FIRST_NAME IS NOT NULL AND CC1.MIDDLE_NAME IS NOT NULL THEN CONCAT(CC1.LAST_NAME, ', ', CC1.FIRST_NAME, ' ', CC1.MIDDLE_NAME) \r\n"
			+ "WHEN CC1.LAST_NAME IS NOT NULL AND CC1.FIRST_NAME IS NOT NULL AND CC1.MIDDLE_NAME IS NULL THEN CONCAT(CC1.LAST_NAME, ', ', CC1.FIRST_NAME)\r\n"
			+ "WHEN CC1.LAST_NAME AND CC1.FIRST_NAME AND CC1.MIDDLE_NAME IS NOT NULL THEN CONCAT(CC1.LAST_NAME, ', ', CC1.FIRST_NAME, ' ', CC1.MIDDLE_NAME)\r\n"
			+ "END AS SOLICITANTE,\r\n" + "CC5.LAST_NAME GRUPO,\r\n" + "UR.SYM URGENCIA,\r\n" + "IM.SYM IMPACTO,\r\n"
			+ "CR.ZDIAG_INICIAL DIAGNOSTICO_INICIAL,\r\n" + "ZD.SYM DIAGNOSTICO_FINAL,\r\n" + "ZS.SYM SOLUCION,\r\n"
			+ "CR.ZFECHA_SOL FECHA_HORA_DE_SOLUCION,\r\n" + "CR.OPEN_DATE FECHA_HORA_DE_APERTURA,\r\n"
			+ "CR.LAST_MOD_DT ULTIMA_MODIFICACIÓN,\r\n" + "CR.RESOLVE_DATE FECHA_HORA_DE_NOTIFICACION_DE_SOLUCION,\r\n"
			+ "CR.CLOSE_DATE Fecha_Hora_de_Cierre,\r\n" + "CR.ZTIEMPO_FALLA_TPE TIEMPO_FALLA_ENLACE,\r\n"
			+ "CR.ZTIEMPO_FALLA_CTE TIEMPO_FALLA_CTE,\r\n" + "OW.RESOURCE_NAME CI,\r\n"
			+ "CR.ZES_PROACTIVO_REACTIVO,\r\n" + "CR.ZTIEMPO_FALLA_PROV TIEMPO_FALLA_PROVEEDOR,\r\n"
			+ "CR.ZTIEMPO_FALLA_TERCEROS TIEMPO_FALLA_TERCEROS,\r\n" + "CR.MACRO_PREDICT_VIOL, \r\n"
			+ "CR.SLA_VIOLATION,\r\n" + "CR.EXTERNAL_SYSTEM_TICKET,\r\n" + "OW.IP_ADDRESS, \r\n"
			+ "OW2.RESOURCE_NAME \r\n" + "FROM \r\n" + "SDM_CALL_REQ CR\r\n"
			+ "LEFT JOIN SDM_CA_CONTACT CC1 ON CR.REQUESTED_BY = CC1.CONTACT_UUID\r\n"
			+ "LEFT JOIN SDM_CA_CONTACT CC2 ON CR.CUSTOMER = CC2.CONTACT_UUID \r\n"
			+ "LEFT JOIN SDM_PROB_CTG PG ON CR.CATEGORY = PG.PERSID\r\n"
			+ "LEFT JOIN SDM_CR_STAT ST ON CR.STATUS = ST.CODE \r\n"
			+ "LEFT JOIN SDM_PRI PR ON CR.PRIORITY = PR.ENUM\r\n"
			+ "LEFT JOIN SDM_CA_CONTACT CC4 ON CR.ASSIGNEE = CC4.CONTACT_UUID\r\n"
			+ "LEFT JOIN SDM_CA_CONTACT CC5 ON CR.GROUP_ID = CC5.CONTACT_UUID\r\n"
			+ "LEFT JOIN SDM_URGNCY UR ON CR.URGENCY = UR.ENUM\r\n"
			+ "LEFT JOIN SDM_IMPACT IM ON CR.IMPACT = IM.ENUM\r\n"
			+ "LEFT JOIN SDM_CA_OWNED_RESOURCE OW ON AFFECTED_RC = OW.OWN_RESOURCE_UUID\r\n"
			+ "LEFT JOIN SDM_ZDIAGNOSTICO ZD ON CR.ZDIAGNOSTICO_ID = ZD.ID \r\n"
			+ "LEFT JOIN SDM_ZSOLUCION ZS ON CR.ZSOLUCION_ID = ZS.ID\r\n"
			+ "LEFT JOIN SDM_CA_TENANT CTN ON CR.TENANT = CTN.ID \r\n"
			+ "LEFT JOIN SDM_BUSMGT BUS ON OW.OWN_RESOURCE_UUID = BUS.hier_child \r\n"
			+ "LEFT JOIN SDM_CA_OWNED_RESOURCE OW2 ON BUS.hier_parent = OW2.OWN_RESOURCE_UUID \r\n"
			+ "WHERE CR.TYPE = 'I'\r\n" + "AND CR.STATUS IN(:status)\r\n" + "AND CR.REQUESTED_BY = :requestBy \r\n"
			+ "AND OW2.INACTIVE = 0 \r\n"
			+ "AND OW2.RESOURCE_CLASS = (SELECT ID FROM SDM_CA_RESOURCE_CLASS WHERE NAME = (:clase)) \r\n"
			+ "ORDER BY CR.OPEN_DATE desc", nativeQuery = true)
	public abstract List<Object> getTicketsStatusAndRequestBys(@Param("status") List<String> status,
			@Param("requestBy") String requestBy,@Param("clase") String clase);

	@Query(value = "select a.ref_num, a.status, a.summary \r\n"
			+ "from datahub.sdm_call_req a left join datahub.sdm_ca_owned_resource b  on a.affected_rc = b.own_resource_uuid\r\n"
			+ "where active_flag = 1\r\n" + "and b.ip_address IN (:ip_address) ", nativeQuery = true)
	public abstract List<Object> getTicketByIP(@Param("ip_address") String ip);

	@Query(value = "select a.ref_num, a.status, a.summary\r\n"
			+ "from datahub.sdm_call_req a left join datahub.sdm_ca_owned_resource b  on a.affected_rc = b.own_resource_uuid\r\n"
			+ "where active_flag = 1\r\n" + "and b.serial_number IN (:serial_number) ", nativeQuery = true)
	public abstract List<Object> getTicketByNumSerial(@Param("serial_number") String numeroSerie);

	
	@Query(value = "SELECT CR.REF_NUM REFNUM, \r\n" + 
			"			OW.RESOURCE_NAME TFE, \r\n" + 
			"			CTN.NAME TENANT, \r\n" + 
			"			CR.SUMMARY RESUMEN, \r\n" + 
			"			PR.SYM PRIORIDAD, \r\n" + 
			"			PG.SYM CATEGORIA, \r\n" + 
			"			ST.SYM ESTADO, \r\n" + 
			"			CASE \r\n" + 
			"			WHEN CC4.LAST_NAME IS NOT NULL AND CC4.FIRST_NAME IS NOT NULL AND CC4.MIDDLE_NAME IS NOT NULL THEN CONCAT(CC4.LAST_NAME, ', ', CC4.FIRST_NAME, ' ', CC4.MIDDLE_NAME) \r\n" + 
			"			WHEN CC4.LAST_NAME IS NOT NULL AND CC4.FIRST_NAME IS NOT NULL AND CC4.MIDDLE_NAME IS NULL THEN CONCAT(CC4.LAST_NAME, ', ', CC4.FIRST_NAME) \r\n" + 
			"			WHEN CC4.LAST_NAME AND CC4.FIRST_NAME AND CC4.MIDDLE_NAME IS NOT NULL THEN CONCAT(CC4.LAST_NAME, ', ', CC4.FIRST_NAME, ' ', CC4.MIDDLE_NAME) \r\n" + 
			"			END ASIGNADO, \r\n" + 
			"			CC4.FIRST_NAME ASIGNADO_PRIMERNOMBRE, \r\n" + 
			"			CC4.MIDDLE_NAME ASIGNADO_SEGUNDONOMBRE, \r\n" + 
			"			CC4.LAST_NAME ASIGNADO_APELLIDO, \r\n" + 
			"			CASE \r\n" + 
			"			WHEN CC2.LAST_NAME IS NOT NULL AND CC2.FIRST_NAME IS NOT NULL AND CC2.MIDDLE_NAME IS NOT NULL THEN CONCAT(CC2.LAST_NAME, ', ', CC2.FIRST_NAME, ' ', CC2.MIDDLE_NAME) \r\n" + 
			"			WHEN CC2.LAST_NAME IS NOT NULL AND CC2.FIRST_NAME IS NOT NULL AND CC2.MIDDLE_NAME IS NULL THEN CONCAT(CC2.LAST_NAME, ', ', CC2.FIRST_NAME) \r\n" + 
			"			WHEN CC2.LAST_NAME AND CC2.FIRST_NAME AND CC2.MIDDLE_NAME IS NOT NULL THEN CONCAT(CC2.LAST_NAME, ', ', CC2.FIRST_NAME, ' ', CC2.MIDDLE_NAME)  \r\n" + 
			"			END Usuario_Final_Afectado_Cliente, \r\n" + 
			"			CC2.FIRST_NAME CLIENTEAFECTADO_PRIMERNOMBRE, \r\n" + 
			"			CC2.MIDDLE_NAME CLIENTEAFECTADO_SEGUNDONOMBRE, \r\n" + 
			"			CC2.LAST_NAME CLIENTEAFECTADO_LAST_NAME,  \r\n" + 
			"			CR.DESCRIPTION, \r\n" + 
			"			CASE \r\n" + 
			"			WHEN CC1.LAST_NAME IS NOT NULL AND CC1.FIRST_NAME IS NOT NULL AND CC1.MIDDLE_NAME IS NOT NULL THEN CONCAT(CC1.LAST_NAME, ', ', CC1.FIRST_NAME, ' ', CC1.MIDDLE_NAME)  \r\n" + 
			"			WHEN CC1.LAST_NAME IS NOT NULL AND CC1.FIRST_NAME IS NOT NULL AND CC1.MIDDLE_NAME IS NULL THEN CONCAT(CC1.LAST_NAME, ', ', CC1.FIRST_NAME) \r\n" + 
			"			WHEN CC1.LAST_NAME AND CC1.FIRST_NAME AND CC1.MIDDLE_NAME IS NOT NULL THEN CONCAT(CC1.LAST_NAME, ', ', CC1.FIRST_NAME, ' ', CC1.MIDDLE_NAME) \r\n" + 
			"			END AS SOLICITANTE, \r\n" + 
			"			CC5.LAST_NAME GRUPO, \r\n" + 
			"			UR.SYM URGENCIA, \r\n" + 
			"			IM.SYM IMPACTO, \r\n" + 
			"			CR.ZDIAG_INICIAL DIAGNOSTICO_INICIAL, \r\n" + 
			"			ZD.SYM DIAGNOSTICO_FINAL, \r\n" + 
			"			ZS.SYM SOLUCION, \r\n" + 
			"			CR.ZFECHA_SOL FECHA_HORA_DE_SOLUCION, \r\n" + 
			"			CR.OPEN_DATE FECHA_HORA_DE_APERTURA, \r\n" + 
			"			CR.LAST_MOD_DT ULTIMA_MODIFICACIÓN, \r\n" + 
			"			CR.RESOLVE_DATE FECHA_HORA_DE_NOTIFICACION_DE_SOLUCION, \r\n" + 
			"			CR.CLOSE_DATE Fecha_Hora_de_Cierre, \r\n" + 
			"			CR.ZTIEMPO_FALLA_TPE TIEMPO_FALLA_ENLACE, \r\n" + 
			"			CR.ZTIEMPO_FALLA_CTE TIEMPO_FALLA_CTE, \r\n" + 
			"			OW.RESOURCE_NAME CI, \r\n" + 
			"			CR.ZES_PROACTIVO_REACTIVO, \r\n" + 
			"			CR.ZTIEMPO_FALLA_PROV TIEMPO_FALLA_PROVEEDOR, \r\n" + 
			"			CR.ZTIEMPO_FALLA_TERCEROS TIEMPO_FALLA_TERCEROS, \r\n" + 
			"			CR.MACRO_PREDICT_VIOL,  \r\n" + 
			"			CR.SLA_VIOLATION, \r\n" + 
			"			CR.EXTERNAL_SYSTEM_TICKET, \r\n" + 
			"			OW.IP_ADDRESS, \r\n" + 
			"			OW2.RESOURCE_NAME ORGANIZACION,\r\n" + 
			"           OW.serial_number NUMERO_SERIE,\r\n" + 
			"           RC.NAME TIPO_DISPOSITIVO\r\n" + 
			"			FROM  \r\n" + 
			"			datahub.SDM_CALL_REQ CR \r\n" + 
			"			LEFT JOIN datahub.SDM_CA_CONTACT CC1 ON CR.REQUESTED_BY = CC1.CONTACT_UUID \r\n" + 
			"			LEFT JOIN datahub.SDM_CA_CONTACT CC2 ON CR.CUSTOMER = CC2.CONTACT_UUID  \r\n" + 
			"			LEFT JOIN datahub.SDM_PROB_CTG PG ON CR.CATEGORY = PG.PERSID \r\n" + 
			"			LEFT JOIN datahub.SDM_CR_STAT ST ON CR.STATUS = ST.CODE  \r\n" + 
			"			LEFT JOIN datahub.SDM_PRI PR ON CR.PRIORITY = PR.ENUM \r\n" + 
			"			LEFT JOIN datahub.SDM_CA_CONTACT CC4 ON CR.ASSIGNEE = CC4.CONTACT_UUID \r\n" + 
			"			LEFT JOIN datahub.SDM_CA_CONTACT CC5 ON CR.GROUP_ID = CC5.CONTACT_UUID \r\n" + 
			"			LEFT JOIN datahub.SDM_URGNCY UR ON CR.URGENCY = UR.ENUM \r\n" + 
			"			LEFT JOIN datahub.SDM_IMPACT IM ON CR.IMPACT = IM.ENUM \r\n" + 
			"			LEFT JOIN datahub.SDM_CA_OWNED_RESOURCE OW ON AFFECTED_RC = OW.OWN_RESOURCE_UUID \r\n" + 
			"			LEFT JOIN datahub.SDM_ZDIAGNOSTICO ZD ON CR.ZDIAGNOSTICO_ID = ZD.ID  \r\n" + 
			"			LEFT JOIN datahub.SDM_ZSOLUCION ZS ON CR.ZSOLUCION_ID = ZS.ID \r\n" + 
			"			LEFT JOIN datahub.SDM_CA_TENANT CTN ON CR.TENANT = CTN.ID  \r\n" + 
			"			LEFT JOIN datahub.SDM_BUSMGT BUS ON OW.OWN_RESOURCE_UUID = BUS.hier_child \r\n" + 
			"			LEFT JOIN datahub.SDM_CA_OWNED_RESOURCE OW2 ON BUS.hier_parent = OW2.OWN_RESOURCE_UUID\r\n" + 
			"            LEFT JOIN datahub.sdm_ca_resource_class RC ON OW.RESOURCE_CLASS = RC.id\r\n" + 
			"			WHERE CR.TYPE = 'I' \r\n" + 
			"			AND CR.STATUS IN(:status) \r\n" + 
			"			AND OW2.RESOURCE_NAME = :resourceName \r\n" + 
			"			AND OW2.INACTIVE = 0 \r\n" + 
			"			AND OW2.RESOURCE_CLASS = (SELECT ID FROM datahub.SDM_CA_RESOURCE_CLASS WHERE NAME = (:clase)) \r\n" + 
			"			ORDER BY CR.OPEN_DATE desc", nativeQuery = true)
	public abstract List<Object> getTicketsStatusAndResourceName(@Param("status") List<String> status,
			@Param("resourceName") String resourceName,@Param("clase") String clase);

}
